#!/bin/bash
# WolfScale Service Installer
# Installs WolfScale as a systemd service
# Run with sudo: sudo ./install_service.sh [node|proxy]

set -e

SERVICE_TYPE="${1:-node}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BINARY="$SCRIPT_DIR/target/release/wolfscale"
SOURCE_CONFIG="$SCRIPT_DIR/wolfscale.toml"
INSTALL_DIR="/opt/wolfscale"
CONFIG="$INSTALL_DIR/wolfscale.toml"
USER="wolfscale"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root: sudo $0 [node|proxy]"
    exit 1
fi

# Check for binary
if [ ! -f "$BINARY" ]; then
    echo "ERROR: WolfScale binary not found at $BINARY"
    echo "Please build first with: cargo build --release"
    exit 1
fi

echo "Installing WolfScale as systemd service ($SERVICE_TYPE mode)..."

# Create user if doesn't exist
if ! id "$USER" &>/dev/null; then
    useradd --system --no-create-home --shell /bin/false "$USER"
    echo "Created user: $USER"
fi

# Create install directory
mkdir -p "$INSTALL_DIR"
mkdir -p /var/lib/wolfscale
mkdir -p /var/log/wolfscale

# Copy binary
cp "$BINARY" "$INSTALL_DIR/wolfscale"
chmod +x "$INSTALL_DIR/wolfscale"

# ============ Configuration Wizard ============
# If no config file exists, ask questions to create one

if [ -f "$SOURCE_CONFIG" ]; then
    cp "$SOURCE_CONFIG" "$CONFIG"
    echo "Using existing configuration from $SOURCE_CONFIG"
elif [ -f "$CONFIG" ]; then
    echo "Using existing configuration at $CONFIG"
else
    echo ""
    echo "No configuration file found. Let's create one!"
    echo "=============================================="
    echo ""
    
    # Node ID
    HOSTNAME=$(hostname)
    read -p "Node ID [$HOSTNAME]: " NODE_ID
    NODE_ID="${NODE_ID:-$HOSTNAME}"
    
    # Bind address
    read -p "Bind address [0.0.0.0:7400]: " BIND_ADDR
    BIND_ADDR="${BIND_ADDR:-0.0.0.0:7400}"
    
    # Is this the bootstrap (first) node?
    read -p "Is this the FIRST node in the cluster? (y/n) [n]: " IS_BOOTSTRAP
    IS_BOOTSTRAP="${IS_BOOTSTRAP:-n}"
    
    # Peer addresses (if not bootstrap)
    PEERS=""
    if [[ "$IS_BOOTSTRAP" != "y" && "$IS_BOOTSTRAP" != "Y" ]]; then
        echo ""
        echo "Enter peer addresses to join the cluster."
        echo "Format: host:port (one per line, press Enter after each)"
        echo "Press Enter on an empty line when done."
        echo ""
        while true; do
            read -p "Peer address: " PEER
            [ -z "$PEER" ] && break
            if [ -z "$PEERS" ]; then
                PEERS="\"$PEER\""
            else
                PEERS="$PEERS, \"$PEER\""
            fi
        done
    fi
    
    echo ""
    echo "Database Configuration"
    echo "======================"
    echo ""
    echo "WolfScale connects to the local MariaDB server and replicates ALL"
    echo "operations to other nodes. Enter the connection details below."
    echo "(The database name is just for the connection - all databases are synced)"
    echo ""
    # Database host
    read -p "MariaDB host [127.0.0.1]: " DB_HOST
    DB_HOST="${DB_HOST:-127.0.0.1}"
    
    # Database port
    read -p "MariaDB port [3306]: " DB_PORT
    DB_PORT="${DB_PORT:-3306}"
    
    # Database user
    read -p "Database user [wolfscale]: " DB_USER
    DB_USER="${DB_USER:-wolfscale}"
    
    # Database password
    read -sp "Database password: " DB_PASS
    echo ""
    
    # API port
    read -p "HTTP API port [8080]: " API_PORT
    API_PORT="${API_PORT:-8080}"
    
    # Proxy port
    read -p "MySQL proxy port [3307]: " PROXY_PORT
    PROXY_PORT="${PROXY_PORT:-3307}"
    
    # Generate config file
    cat > "$CONFIG" << EOF
# WolfScale Configuration
# Generated by install_service.sh

[node]
id = "$NODE_ID"
bind_address = "$BIND_ADDR"
data_dir = "/var/lib/wolfscale/$NODE_ID"

[database]
host = "$DB_HOST"
port = $DB_PORT
user = "$DB_USER"
password = "$DB_PASS"
pool_size = 10

[wal]
batch_size = 1000
compression = true
segment_size_mb = 64
fsync = true

[cluster]
peers = [$PEERS]
heartbeat_interval_ms = 500
election_timeout_ms = 2000
disable_auto_election = false

[api]
enabled = true
bind_address = "0.0.0.0:$API_PORT"

[proxy]
enabled = true
bind_address = "0.0.0.0:$PROXY_PORT"
EOF

    echo ""
    echo "Configuration saved to $CONFIG"
fi

# Set permissions
chown -R "$USER:$USER" "$INSTALL_DIR"
chown -R "$USER:$USER" /var/lib/wolfscale
chown -R "$USER:$USER" /var/log/wolfscale

# Determine if bootstrap mode is needed
BOOTSTRAP_FLAG=""
if [[ "$IS_BOOTSTRAP" == "y" || "$IS_BOOTSTRAP" == "Y" ]]; then
    BOOTSTRAP_FLAG="--bootstrap"
fi

# Create systemd service
# Note: Proxy is now built-in to the node, no separate service needed
SERVICE_NAME="wolfscale"
EXEC_START="$INSTALL_DIR/wolfscale --config $CONFIG start $BOOTSTRAP_FLAG"
DESCRIPTION="WolfScale Distributed Database Manager"

cat > "/etc/systemd/system/${SERVICE_NAME}.service" << EOF
[Unit]
Description=$DESCRIPTION
After=network.target mariadb.service
Wants=mariadb.service

[Service]
Type=simple
User=$USER
Group=$USER
WorkingDirectory=$INSTALL_DIR
ExecStart=$EXEC_START
Restart=always
RestartSec=5
StandardOutput=append:/var/log/wolfscale/${SERVICE_NAME}.log
StandardError=append:/var/log/wolfscale/${SERVICE_NAME}.error.log

# Security
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/wolfscale /var/log/wolfscale

[Install]
WantedBy=multi-user.target
EOF

# Reload systemd
systemctl daemon-reload

# Enable and start the service
echo "Enabling and starting service..."
systemctl enable "$SERVICE_NAME"
systemctl start "$SERVICE_NAME"

# Wait a moment for startup
sleep 2

# Check if service started successfully
if systemctl is-active --quiet "$SERVICE_NAME"; then
    echo ""
    echo "=============================================="
    echo "WolfScale installed and running!"
    echo "=============================================="
else
    echo ""
    echo "=============================================="
    echo "WolfScale installed (service may need attention)"
    echo "=============================================="
    echo ""
    echo "Check logs: sudo journalctl -u $SERVICE_NAME -n 50"
fi

echo ""
echo "Configuration: $CONFIG"
echo "Data directory: /var/lib/wolfscale"
echo "Logs: /var/log/wolfscale/"
echo ""
echo "Commands:"
echo "  sudo systemctl status $SERVICE_NAME    # Check status"
echo "  sudo systemctl restart $SERVICE_NAME   # Restart service"
echo "  sudo journalctl -u $SERVICE_NAME -f    # View logs"
echo ""
echo "To edit configuration:"
echo "  sudo nano $CONFIG"
echo "  sudo systemctl restart $SERVICE_NAME"
